-- JustSplit outgrows the fixed-two-users assumption: trips can now have any
-- number of participants, and new companions can be added on the fly.

-- users.id was a plain smallint PK with no sequence (rows 1/2 were inserted
-- explicitly). Give it an identity so app code can create new users without
-- picking an id itself, continuing on from the existing max id.
alter table users alter column id add generated by default as identity;
select setval(
  pg_get_serial_sequence('users', 'id'),
  (select coalesce(max(id), 0) from users)
);

create table if not exists trip_participants (
  trip_id uuid not null references trips(id) on delete cascade,
  user_id smallint not null references users(id),
  primary key (trip_id, user_id)
);

create index if not exists trip_participants_user_id_idx on trip_participants(user_id);

-- Backfill: every trip that exists today implicitly involved both of the
-- app's (only, at this point) two users. Preserve that as explicit rows.
insert into trip_participants (trip_id, user_id)
select t.id, u.id from trips t cross join users u
on conflict do nothing;

alter table trip_participants enable row level security;
